version: '3'
services:
  api:
    container_name: mgr_api
    build: ./api
    volumes:
      - ./api:/go/src/api
    ports:
      - 1323:1323
    tty: true
    depends_on:
      - db
  db:
    container_name: mgr_db
    image: mysql:5.7
    env_file:
      - ./db/db.env
    volumes:
      - db-data:/var/lib/mysql
    tty: true
volumes:
  db-data: