version: '3'
services:
  nuxt:
    container_name: mgr_nuxt
    build: ./front
    working_dir: /front/musicgameranking/
    command: yarn dev
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - api
  api:
    container_name: mgr_api
    build: ./api
    working_dir: /go/src/api
    command: go run server.go
    volumes:
      - ./api:/go/src/api
    ports:
      - 1323:1323
    tty: true
    depends_on:
      - db
  db:
    container_name: mgr_db
    image: mysql:5.7
    env_file:
      - ./db/db.env
    volumes:
      - db-data:/var/lib/mysql
    tty: true
volumes:
  db-data: